### ISSUE TITLE
Add pagination information to the response headers

### ISSUE THREAD

**Issue by stewartduffy** [chrisjm/openbrewerydb-rails-api#39] opened 2020-03-06 01:27 UTC
Not sure if I should raise this as a bug or feature request. It would be great if the pagination information was added to the response headers to be used in conjunction with the the `page` and `per_page` params`. Stuff like total_count so if using this to build a UI it can be used to build the pagination controls.

Thanks :)

**Comment by chrisjm** [comment] 2020-03-06 20:26
This is a duplicate of #31

**Closed by chrisjm** 2020-03-06 20:26 UTC
Labels: duplicate

**Comment by stewartduffy** [comment] 2020-03-06 21:03
Hi @chrisjm this is awesome! Cool yeah I have never done ruby, but more of a JavaScript dev but could have ago! Might read up on it. 
Defiantly will contribute to the dataset though, have been compiling a bunch of data on no breweries but wasn’t sure what do do with it (dB wise) but this answers my questions! Question about some workflow. What do you use to curate edit the data? I see there are tasks for importing / exporting to from json, csv, and the data set. But if today you wanted to add another brewery, what would your work flow be?

For me I have it all sitting in a geoJson that I converted from a KMZ file (exported from - custom google maps). So I can write the task to convert the geoJson. But curious about your work flow.

Cheers again! Looking forward to working on this 🍺🍻

**Comment by chrisjm** [comment] 2020-03-06 23:41
Hi, @stewartduffy!

Definitely depends on the number of breweries you want to add. For adding NZ, you'll need to fork the dataset repo, add a new `nz` country directory under `/data`, and then directories for each region. You can find the schema for each brewery by looking at existing data. 

Does that help?

I'll work on writing up better instructions for contributing to the dataset soon as I know documentation is lacking.

🍻
